title: The goal is always progress.
author: Sherrod Harris
email: harris.d.sherrod@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have found myself searching for improvement as I have gotten older. Looking forward to exploring the future with my strong desire to learn.
theme: minima
# social links
twitter_username: sherrodharris # DO NOT include the @ character, or else the build will fail!
github_username:  sherrodharris # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
